export var CallToActions;
(function (CallToActions) {
    CallToActions[CallToActions["COMPLETE_COMPANY_PROFILE_AND_UPGRADE_SUBSCRIPTION_PLAN"] = 0] = "COMPLETE_COMPANY_PROFILE_AND_UPGRADE_SUBSCRIPTION_PLAN";
    CallToActions[CallToActions["COMPLETE_COMPANY_PROFILE"] = 1] = "COMPLETE_COMPANY_PROFILE";
    CallToActions[CallToActions["UPGRADE_SUBSCRIPTION_PLAN"] = 2] = "UPGRADE_SUBSCRIPTION_PLAN";
    CallToActions[CallToActions["COMPANY_ADD_PAYMENT_DETAILS_TO_UNLOCK_MORE_FEATURES"] = 3] = "COMPANY_ADD_PAYMENT_DETAILS_TO_UNLOCK_MORE_FEATURES";
    CallToActions[CallToActions["COMPANY_SUBSCRIPTION_OUTSTANDING"] = 4] = "COMPANY_SUBSCRIPTION_OUTSTANDING";
    CallToActions[CallToActions["COMPANY_OWNERSHIP_NEEDS_CONFIRMATION"] = 5] = "COMPANY_OWNERSHIP_NEEDS_CONFIRMATION";
    CallToActions[CallToActions["MOD_PRODUCT_READY_FOR_SALE"] = 6] = "MOD_PRODUCT_READY_FOR_SALE";
    CallToActions[CallToActions["CREATE_STORE_FOR_SELLING"] = 7] = "CREATE_STORE_FOR_SELLING";
    CallToActions[CallToActions["COMPANY_NEEDS_TO_ADD_PAYMENT_METHOD"] = 8] = "COMPANY_NEEDS_TO_ADD_PAYMENT_METHOD";
    CallToActions[CallToActions["YOUR_COMPANIES_NEED_STRIPE_TO_COLLECT_PAYMENT"] = 9] = "YOUR_COMPANIES_NEED_STRIPE_TO_COLLECT_PAYMENT";
    CallToActions[CallToActions["SUPPLIER_PRODUCT_READY_FOR_SALE"] = 10] = "SUPPLIER_PRODUCT_READY_FOR_SALE";
    CallToActions[CallToActions["SET_PASSWORD"] = 11] = "SET_PASSWORD";
})(CallToActions || (CallToActions = {}));
