export var JobType;
(function (JobType) {
    JobType[JobType["PRODUCT_CREATION_MOD"] = 0] = "PRODUCT_CREATION_MOD";
    JobType[JobType["PRODUCT_CREATION"] = 1] = "PRODUCT_CREATION";
    JobType[JobType["PRODUCT_RESELL_CREATION_MOD"] = 2] = "PRODUCT_RESELL_CREATION_MOD";
    JobType[JobType["PRODUCT_RESELL_CREATION"] = 3] = "PRODUCT_RESELL_CREATION";
    JobType[JobType["SELLER"] = 4] = "SELLER";
    JobType[JobType["SELLER_MOD"] = 5] = "SELLER_MOD";
    JobType[JobType["SELLER_GROUP_BUY"] = 6] = "SELLER_GROUP_BUY";
    JobType[JobType["SELLER_FILE_DOWNLOAD"] = 7] = "SELLER_FILE_DOWNLOAD";
    JobType[JobType["SUPPLIER_FULFILLMENT"] = 8] = "SUPPLIER_FULFILLMENT";
    JobType[JobType["SUPPLIER_FULFILLMENT_RESELL"] = 9] = "SUPPLIER_FULFILLMENT_RESELL";
    JobType[JobType["SUPPLIER_FULFILLMENT_INVENTORY"] = 10] = "SUPPLIER_FULFILLMENT_INVENTORY";
    JobType[JobType["SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY"] = 11] = "SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY";
    JobType[JobType["SUPPLY_CHAIN_CREATION"] = 12] = "SUPPLY_CHAIN_CREATION"; // USED TO ID JOBS WHICH ARE TO CREATE A NEW SUPPLY CHAIN
})(JobType || (JobType = {}));
