export var ProductType;
(function (ProductType) {
    ProductType[ProductType["SUPPLIER_MOD"] = 0] = "SUPPLIER_MOD";
    ProductType[ProductType["SUPPLIER"] = 1] = "SUPPLIER";
    ProductType[ProductType["SELLER"] = 2] = "SELLER";
    ProductType[ProductType["SELLER_MOD"] = 3] = "SELLER_MOD";
    ProductType[ProductType["CLONED_SUPPLIER_MOD"] = 4] = "CLONED_SUPPLIER_MOD";
    ProductType[ProductType["CLONED_SELLER_MOD"] = 5] = "CLONED_SELLER_MOD";
    ProductType[ProductType["PRODUCTION_MOD"] = 6] = "PRODUCTION_MOD";
    ProductType[ProductType["CLONED_SUPPLIER"] = 7] = "CLONED_SUPPLIER";
    ProductType[ProductType["INVENTORY_SELLER"] = 8] = "INVENTORY_SELLER";
    ProductType[ProductType["INVENTORY_SUPPLIER"] = 9] = "INVENTORY_SUPPLIER";
    ProductType[ProductType["SELLER_GROUP_BUY"] = 10] = "SELLER_GROUP_BUY";
    ProductType[ProductType["SUPPLIER_RESELL_MOD"] = 11] = "SUPPLIER_RESELL_MOD";
    ProductType[ProductType["SUPPLIER_RESELL"] = 12] = "SUPPLIER_RESELL";
    ProductType[ProductType["SUPPLIER_GROUP_BUY_INVENTORY"] = 13] = "SUPPLIER_GROUP_BUY_INVENTORY";
    ProductType[ProductType["CLONED_INVENTORY_SELLER"] = 14] = "CLONED_INVENTORY_SELLER";
    ProductType[ProductType["CLONED_SELLER_GROUP_BUY_INVENTORY"] = 15] = "CLONED_SELLER_GROUP_BUY_INVENTORY";
    ProductType[ProductType["CLONED_SUPPLIER_RESELL_MOD"] = 16] = "CLONED_SUPPLIER_RESELL_MOD";
    ProductType[ProductType["SUPPLIER_TO_SUPPLIER_RESELL_MOD"] = 17] = "SUPPLIER_TO_SUPPLIER_RESELL_MOD";
    ProductType[ProductType["CLONED_SUPPLIER_RESELL"] = 18] = "CLONED_SUPPLIER_RESELL";
    ProductType[ProductType["SUPPLY_DOMAIN_REFERENCE"] = 19] = "SUPPLY_DOMAIN_REFERENCE";
    ProductType[ProductType["SELLER_FILE_DOWNLOAD"] = 20] = "SELLER_FILE_DOWNLOAD";
    ProductType[ProductType["SUPPLIER_MOD_SUPPLY_CHAIN_REQUEST"] = 21] = "SUPPLIER_MOD_SUPPLY_CHAIN_REQUEST";
    ProductType[ProductType["SUPPLIER_SUPPLY_CHAIN_REQUEST"] = 22] = "SUPPLIER_SUPPLY_CHAIN_REQUEST";
})(ProductType || (ProductType = {}));
